### ISSUE TITLE
大神，什么时候公开你的代码呢 ：）

### ISSUE THREAD

**Issue by cooliean** [Feemic/mooc_tool_source#2]
好想学习一下你的
http://www.feemic.cn/mooc_search/1002216001
这个页面是怎么做的。

我搜索课程，实现了，但是后面的不知道怎么做了。。。

**Comment by cooliean** [comment]
或者给我说说原理吧   ：），我看到好像可以循环请求

https://www.icourse163.org/dwr/call/plaincall/CourseBean.getLessonUnitLearnVo.dwr

但是不知道有么有其它方法

**Comment by Feemic** [comment]
@cooliean 
搜索课程得到对应的id，再根据id进行解析就行了。最近有点忙，代码估计要等新版本上线一段时间才提交，新版本上线可能也要一段时间了，，

**Comment by cooliean** [comment]
好的，谢谢了

**Comment by cooliean** [comment]
其实刚才看到你更新了，好高兴，结果是更新了一行readme  ：）
